version: 2.1

executors:
  node-executor:
    docker:
      - image: circleci/node:8.15.1-stretch-browsers-legacy
    working_directory: /tmp/workspace

jobs:
  build:
    executor: node-executor
    working_directory: /tmp/workspace/farmsmart
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ .Branch }}
      - run:
          working_directory: /tmp/workspace/farmsmart/functions
          name: install firebase
          command: npm install --save-dev firebase-tools
      - run:
          working_directory: /tmp/workspace/farmsmart/functions
          name: update firebase
          command: npm install firebase-admin@latest firebase-functions@latest
      - run:
          working_directory: /tmp/workspace/farmsmart/functions
          name: install app dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ .Branch }}
          paths:
            - /tmp/workspace/farmsmart/functions/.node_modules
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - farmsmart
  test:
    executor: node-executor
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run:
          working_directory: /tmp/workspace/farmsmart/functions
          name: code base lint
          command: |
            npm run-script lint
            npm run-script test   

  deploy:
    executor: node-executor
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run:
          working_directory: /tmp/workspace/farmsmart/functions
          name: deploy firebase
          command: npm run --silent deploy -- --token $FIREBASE_TOKEN --project $FIREBASE_PROJECT

workflows:
  version: 2
  backend:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          # Uses a context that encapsulates firebase login and project for dev env
          name: deploy-to-dev
          context: farmsmart_dev
          requires:
            - test
          filters:
            branches:
              only:
                - /feature.*/
      - deploy:
          # Uses a context that encapsulates firebase login and project for pre-prod env
          name: deploy-to-preprod
          context: farmsmart_pre_prod
          requires:
            - test
          filters:
            branches:
              only:
                - develop
