version: 2.1

executors:
  node-executor:
    docker:
      - image: circleci/node:8.15.1-stretch-browsers-legacy
    working_directory: /tmp/workspace

jobs:
  build:
    executor: node-executor
    working_directory: /tmp/workspace/farmsmart
    steps:
      - checkout
      - run:
          name: "pull submodules"
          command: |
            git submodule update --init --recursive
      - restore_cache:
          key: dependency-cache-{{ .Branch }}-{{ checksum "/tmp/workspace/farmsmart/functions/package.json" }}
      - run:
          working_directory: /tmp/workspace/farmsmart/functions
          name: update firebase
          command: npm install firebase-admin@latest firebase-functions@latest
      - run:
          working_directory: /tmp/workspace/farmsmart/functions
          name: install app dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ .Branch }}-{{ checksum "/tmp/workspace/farmsmart/functions/package.json" }}
          paths:
            - /tmp/workspace/farmsmart/functions/node_modules
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - farmsmart
  test:
    executor: node-executor
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run:
          working_directory: /tmp/workspace/farmsmart/functions
          name: code base lint
          command: |
            npm run-script lint
            npm run-script test:ci
      - store_test_results:
          path: /tmp/workspace/farmsmart/functions/reports

  deploy:
    executor: node-executor
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run:
          working_directory: /tmp/workspace/farmsmart/functions
          name: deploy firebase
          command: |
            SECRETS_DIR=./.credentials
            mkdir -p ${SECRETS_DIR}
            echo "Set firebase project config"
            npm run --silent set:config -- --token $FIREBASE_TOKEN --project $FIREBASE_PROJECT farmsmart.sheets.jsonauth="auth.json"
            npm run --silent set:config -- --token $FIREBASE_TOKEN --project $FIREBASE_PROJECT farmsmart.sheets.api.key=${SHEETS_API_KEY}
            npm run --silent set:config -- --token $FIREBASE_TOKEN --project $FIREBASE_PROJECT farmsmart.scorematrix.doc.id=${SCORE_DOC_ID}

            echo "deploy"
            echo ${SHEETS_SERVICE_ACCOUNT} | base64 -di > ${SECRETS_DIR}/auth.json
            file /tmp/workspace/farmsmart/functions/.credentials/auth.json
            npm run --silent deploy -- --token $FIREBASE_TOKEN --project $FIREBASE_PROJECT --force

workflows:
  version: 2
  backend:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          # Uses a context that encapsulates firebase login and project for dev env
          name: deploy-to-dev
          context: farmsmart_dev
          requires:
            - test
          filters:
            branches:
              only:
                - /feature.*/
      - deploy:
          # Uses a context that encapsulates firebase login and project for pre-prod env
          name: deploy-to-preprod
          context: farmsmart_pre_prod
          requires:
            - test
          filters:
            branches:
              only:
                - develop
