version: 2.1

references: 
  working_dir: &working_dir /tmp/workspace/farmsmart
  
  functions_dir: &functions_dir /tmp/workspace/farmsmart/functions

  rules_dir: &rules_dir /tmp/workspace/farmsmart/rules

  workspace: &workspace /tmp/workspace

  restore_workspace: &restore_workspace
    attach_workspace:
      at: *workspace

  save_workspace: &save_workspace
    persist_to_workspace:
      root: *workspace
      paths:
        - farmsmart

executors:
  farmsmart-executor:
    docker:
      - image: farmsmart/gcp-firebase:gcloud252-node10-firebase7.0.2
    working_directory: *working_dir

jobs:
  build:
    executor: farmsmart-executor
    steps:
      - checkout
      - run:
          name: "pull submodules"
          command: |
            git submodule update --init --recursive --remote
      
      - run:
          working_directory: *functions_dir
          name: Install dependencies for cloud function
          command: | 
            npm install firebase-admin@latest firebase-functions@latest
            npm install

      - run:
          working_directory: *rules_dir
          name: Install dependencies for rules
          command: |
            npm install

      - *save_workspace
    
  test:
    executor: farmsmart-executor
    steps:
      - *restore_workspace
      - run:
          working_directory: *functions_dir
          name: Run unit tests on cloud functions
          command: |
            npm run-script lint
            npm run-script test:ci
      # requires login and emulator
      #- run:
      #    working_directory: *rules_dir
      #    name: Run unit tests for the rules
      #    command: |
      #      npm run-script test
      - store_test_results:
          path: /tmp/workspace/farmsmart/functions/reports

  deploy:
    executor: farmsmart-executor
    steps:
      - *restore_workspace

      - run:
          working_directory: *functions_dir
          name: Inject credential for spreadsheet user
          command: |
            set -euo pipefail
            secrets_dir='.credentials'
            mkdir -p ${secrets_dir}
            echo ${SHEETS_SERVICE_ACCOUNT} | base64 -di > ${secrets_dir}/recommendations-service-account.json

      - run:
          working_directory: *working_dir
          name: Deploy to firebase project
          command: |
            set -euo pipefail
            echo "Set firebase project cloud function configs"
            
            firebase functions:config:set --token $FIREBASE_TOKEN --project $FIREBASE_PROJECT farmsmart.sheets.api.key=${SHEETS_API_KEY}
            firebase functions:config:set --token $FIREBASE_TOKEN --project $FIREBASE_PROJECT farmsmart.scorematrix.doc.id=${SCORE_DOC_ID}
            firebase functions:config:set --token $FIREBASE_TOKEN --project $FIREBASE_PROJECT farmsmart.slack.api.token=${SLACK_FARMSMART_TOKEN}

            echo "Deploy all FireBase artifacts (cloud functions, rules, hosting)"
            
            firebase deploy --token $FIREBASE_TOKEN --project $FIREBASE_PROJECT --force

  integration:
    executor: farmsmart-executor
    steps:
      - run:
          name: Test integration of spreadsheets
          command: | 
            set -euo pipefail

            curl --silent $BULKUPLOAD_URL | grep -v FAILED

workflows:
  version: 2
  backend:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          # Deploys feature branches to gcp project
          name: deploy-gcp-feature
          context: gcp-feature
          requires:
            - test
          filters:
            branches:
              only:
                - /feature.*/
      - deploy:
          # Deploys develop branch to gcp project
          name: deploy-gcp-dev
          context: gcp-dev
          requires:
            - test
          filters:
            branches:
              only:
                - develop
      - deploy:
          # Deploys release branches to gcp project
          name: deploy-gcp-stage
          context: gcp-stage
          requires:
            - test
          filters:
            branches:
              only:
                - /release.*/
      - deploy:
          # Deploys master to gcp project
          name: deploy-gcp-prod
          context: gcp-prod
          requires:
            - test
          filters:
            branches:
              only:
                - master

      - integration:
          name: int-feature
          context: gcp-feature
          requires:
            - deploy-gcp-feature

      - integration:
          name: int-dev
          context: gcp-dev
          requires:
            - deploy-gcp-dev

      - integration:
          name: int-stage
          context: gcp-stage
          requires:
            - deploy-gcp-stage

      - integration:
          name: int-prod
          context: gcp-prod
          requires:
            - deploy-gcp-prod
